name: Run CI Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Compile
        run: go build ./...
      - name: Test
        run: go test -v -race ./...
