name: Run CI Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19
      - name: Compile
        run: go build ./...
      - name: Test
        run: go test -v -race ./...
